version: "3.8"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pgdata_backend:/var/lib/postgresql/data

  backend:
    build: .
    image: secure-software-backend:latest
    environment:
      PORT: 4000
      PGHOST: db
      PGPORT: 5432
      PGUSER: app
      PGPASSWORD: app
      PGDATABASE: app
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata_backend:
